language: csharp
mono: none
dist: xenial
dotnet: 5.0.100
env:
  DOTNET_CLI_TELEMETRY_OPTOUT=1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test dck_pihole2influx.test/dck_pihole2influx.test.csproj
