language: csharp
mono: none
dist: bionic
dotnet: 5.0.100
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test dck_pihole2influx.test/dck_pihole2influx.test.csproj
