image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

variables: 
  deployDir: "dck_pihole2influx"
  testDir: "dck_pihole2influx.test"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

build:
  stage: build
  script:
    - "pwd"
    - "cd $deployDir"
    - "dotnet restore"
    - "dotnet build"

test:
  stage: test
  script:
    - "pwd"
    - "cd $testDir"
    - "dotnet restore"
    - "dotnet test /p:CollectCoverage=true"
