FROM ubuntu
MAINTAINER Laszlo Lueck <llueck@gmail.com>
RUN pwd
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y apt-transport-https
RUN apt-get install -y wget
RUN wget "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
RUN ls -lah
RUN dpkg --install ./packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y dotnet-sdk-3.1
COPY bin/Release/netcoreapp3.1/publish/ App/
WORKDIR /App
ENTRYPOINT ["dotnet", "dck_pihole2influx.dll"]