{
 "title": "Pihole2Influx",
 "tags": [
  "pihole",
  "influx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Current Pi Hole Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "position" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "topclient",
     "select": [
      [
       { "params": [ "clientIp" ], "type": "field" }
      ],
      [
       { "params": [ "hostName" ], "type": "field" }
      ],
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "position" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "topads",
     "select": [
      [
       { "params": [ "position" ], "type": "field" }
      ],
      [
       { "params": [ "iporhost" ], "type": "field" }
      ],
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "position" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "topdomains",
     "select": [
      [
       { "params": [ "position" ], "type": "field" }
      ],
      [
       { "params": [ "iporhost" ], "type": "field" }
      ],
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Domains in blocklist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "domainsBeingBlocked" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQLite Database size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseFileSize" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries served from cache",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesCached" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "dnsQueriesToday" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "dnsType" ], "type": "tag" }
     ],
     "measurement": "querytype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries in cache",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheInserted" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQLite Database entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseEntries" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries forwarded to external dns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesForwarded" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "dnsType" ], "type": "tag" }
     ],
     "measurement": "querytype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pi Hole Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "alias": "Default CacheSize",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cacheentries inserted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheInserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cache Live Freed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheLiveFreed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Querydistribution cached vs. forwarded",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Queries cached",
     "measurement": "stats",
     "query": "SELECT \"queriesCached\" FROM \"stats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "queriesCached" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Queries forwarded",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesForwarded" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries and ads in between 24h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Ads blocked in between 24h",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "adsBlockedToday" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "DNS queries in between 24h",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "dnsQueriesToday" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Queries per 10 mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "overtime",
     "select": [
      [
       { "params": [ "blockValue" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "permitValue" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overtime",
     "query": "SELECT median(\"blockValue\") + median(\"permitValue\") as \"sumOfBoth\" FROM \"overtime\" WHERE $timeFilter GROUP BY time(10m)",
     "select": [
      [
       { "params": [ "blockValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "permitValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "ipOrHostName" ], "type": "tag" }
     ],
     "measurement": "forwardDestinations",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Clients ever seen",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "clientsEverSeen" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unique clients atm",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "uniqueClients" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}