{
 "title": "pihole2influx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "position" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "topclient",
     "select": [
      [
       { "params": [ "clientIp" ], "type": "field" }
      ],
      [
       { "params": [ "hostName" ], "type": "field" }
      ],
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Current Pi Hole Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQLite Database size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseFileSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "dnsType" ], "type": "tag" }
     ],
     "measurement": "querytype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries cached (last 24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "SQLite database size over time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseFileSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Queries cached (last 24h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesCached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQLite Database entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseEntries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "dnsType" ], "type": "tag" }
     ],
     "measurement": "querytype",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pi Hole Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "alias": "Default CacheSize",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cacheentries inserted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheInserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cache Live Freed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cacheinfo",
     "select": [
      [
       { "params": [ "cacheLiveFreed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "SQLite database entries over time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dbstats",
     "select": [
      [
       { "params": [ "databaseEntries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries cached vs. forwarded",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Queries cached",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesCached" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Queries forwarded",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "queriesForwarded" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries and ads in between 24h",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Ads blocked in between 24h",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stats",
     "select": [
      [
       { "params": [ "adsBlockedToday" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DNS queries in between 24h",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "stats",
     "select": [
      [
       { "params": [ "dnsQueriesToday" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Queries per 10 mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "overtime",
     "select": [
      [
       { "params": [ "blockValue" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "permitValue" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Clients ever seen",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "clientsEverSeen" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unique clients atm",
     "measurement": "stats",
     "select": [
      [
       { "params": [ "uniqueClients" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "ipOrHostName" ], "type": "tag" }
     ],
     "measurement": "forwardDestinations",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" }
      ],
      [
       { "params": [ "ipOrHostName" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}